version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
      args:
        GOOGLE_ANALYTICS: ""
        WEB_SERVICE_USER: ${WEB_SERVICE_USER}
        WEB_SERVICE_PASSWORD: ${WEB_SERVICE_PASSWORD}
    depends_on:
      - web-server
    ports:
      - "8020:80"
  rabbitmq:
    build:
      context: ./
      dockerfile: ./rabbitmq/Dockerfile
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
  flower:
    build: https://github.com/mher/flower.git
    command: "celery flower --url_prefix=service/flower"
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
    depends_on:
      - rabbitmq
  web-server:
    build:
      context: ./
      dockerfile: ./web-server/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - rabbitmq
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
      PRANKWEB_DATA: "/data/prankweb"
    volumes:
      - predictions:/data/prankweb
  executor:
    build:
      context: ./
      dockerfile: ./executor/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - rabbitmq
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
    volumes:
      - conservation:/data/conservation
      - predictions:/data/prankweb
volumes:
  rabbitmq:
    external: True
    name: prankweb_rabbitmq
  conservation:
    external: True
    name: prankweb_conservation
  predictions:
    external: True
    name: prankweb_predictions
