version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
      args:
        GOOGLE_ANALYTICS: ""
        WEB_SERVICE_USER: ${WEB_SERVICE_USER}
        WEB_SERVICE_PASSWORD: ${WEB_SERVICE_PASSWORD}
    depends_on:
      - web-server
    ports:
      - "8020:80"
  rabbitmq:
    build:
      context: ./
      dockerfile: ./rabbitmq/Dockerfile
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 30s
      retries: 3
  flower:
    build: https://github.com/mher/flower.git
    command: "celery flower --url_prefix=service/flower"
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
    depends_on:
      rabbitmq:
          condition: service_healthy
  web-server:
    build:
      context: ./
      dockerfile: ./web-server/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
      PRANKWEB_DATA: "/data/prankweb"
    volumes:
      - predictions:/data/prankweb
  executor-p2rank:
    build:
      context: ./
      dockerfile: ./executor-p2rank/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
    volumes:
      - conservation:/data/conservation
      - predictions:/data/prankweb
  prometheus:
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile
    volumes:
      - services:/data
    depends_on:
      - flower
      - rabbitmq
    restart: unless-stopped
    ports:
      - "9090:9090"
volumes:
  rabbitmq:
    external: True
    name: prankweb_rabbitmq
  conservation:
    external: True
    name: prankweb_conservation
  predictions:
    external: True
    name: prankweb_predictions
  services:
    external: True
    name: prankweb_services
