global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: flower
    static_configs:
      - targets: ["flower:5555"]
    metrics_path: "/service/flower/metrics"
  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
